### ISSUE TITLE
Design idea / Columns view with infinite scroll

### ISSUE THREAD

**Issue by TtuxX** [callmemagnus/nextcloud-searchpage#1]
Hello Magnus, 

Thank you very much for this new app that seems promising and much needed! :)

Would it be possible to have a sort of vertical view to make a better use of available screen space when using a computer ?
The number of displayed apps would ideally be responsive according to the screen size.

You will kindly find hereunder a design idea, I don't know however if it would be appropriate, suit your vision, and (if so) how hard it would be to implement :/

Thank you very much :)

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/6570830/e17e0ff1-8dda-4969-9b76-214630d6be40)

**Comment by callmemagnus** [comment]
Interesting thanks!

I agree that the current layout is abusing the screen real estate when the resolution are high!

Currently the order of search providers (~ application) is dictated by Nextcloud. I don't even know where that can be changed.

Looking at your mockup, I wonder if I like the fixed height boxes. And if it does not defeat the purpose of showing a scanable list of results. But on the other hand, a button on the top might provide a way to switch to focus on one provider/application results. 

I'll dig into it!

**Comment by callmemagnus** [comment]
Check v1.1.0

**Comment by TtuxX** [comment]
This is awesome, thank you very much ! :)

It brings few questions/feedbacks to me:
- Would it be possible to preload a bit more/more early next results when scrolling ? To make it more fluid and give a better sense of "infinity scrolling" (for example, Files on my instance takes a bit of time to load the next results)
- When scrolling isolated Files results or some other ones, the Back button does not stick to its top position on scroll, requiring user to scroll up in the opposite direction to find it again
- Would it be possible to trigger search immediately after last letter input ? It would remove the "Search" button, make the experience even more fluid and mimic the behaviour of Nextcloud's search button 
- Would it also be possible to transform the "Delete" button into a X cross embedded on the inside-right of the input field like current Nextcloud search button ?

Another idea to make your app even greater would be to directly embed the "..." actions dots that we can find in the Files app for each file/result. That way, the end-user could directly do nearly everything right from the Search page (download and share files, calendar events, bookmarks...) instead of having to load each specific application.
The "..." menu could ideally be app-specific by calling each app's typical details menu, but I have no clue if this is even technically achievable and I am afraid of how much of an maintenance nightmare it could become.
