### ISSUE TITLE
Add translation for the pop-up helpers for the buttons Back and Show only

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#10]
Please, add the localisation for pop-up helpers for the buttons "Back" and "Show only" to the code.

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/18710fa7-4e21-4c89-a08f-cd5f9861b773)

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/8b10b74d-9226-401c-84f9-f03e0a3a6028)

**Comment by callmemagnus** [comment]
@ostasevych  Can you squash all your changes `.js` `.json`, `.po` and `.php` in one PR ?

Also add the Back to the other files.

Thanks in advance !

**Comment by callmemagnus** [comment]
done. Please check v1.2.0-pre on develop
