### ISSUE TITLE
The provider name is still All providers when clicking show only and going to a separate page

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#11]
When I click "Show only" button to view the data provided by one separate provider the field with the selection of providers still shows "All providers", though it should be changed to the name of the selected provider. So, there's lack in inheriting the selected provider.

**Comment by callmemagnus** [comment]
It is "by design" as it's just a kind of zoom.

I'm looking into reduce the importance of the selection of providers so this might become irrelevant.

**Comment by ostasevych** [comment]
> It is "by design" as it's just a kind of zoom.
Well, it's a bit confusing, to be honest 😏
> 
> I'm looking into reduce the importance of the selection of providers so this might become irrelevant.
True, some of the providers may be useful only for admins (eg, searching across users), and others may have lower priority (settings, apps).

**Comment by callmemagnus** [comment]
As the providers are supposed to apply security, I would safely think that no relevant results will be returned for non admins.

On the other hand, this application takes its root in:

1. make the existing search bigger and easier to use
2. enable to see results from `fulltextsearch` and `files` together.
3. 

The rest is mostly side-effects :-)
