### ISSUE TITLE
Improve the layout of the search page

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#12]
Please, make slight improvements to the matrix page:
1. Centralise the title, the Search field, Search button, and the Clear button
2. Take away Clear button as it is not functional mostly
3. Make the search field wider to place there longer request
4. Make the height of the text frames equal to the maximum filled on
5. Add more space between matrix frames
7. Separate localisations for the title (Search) and the name of the button Search, as in other languages they may have different modality. 

Please compare
Currently:
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/8e3f6760-b580-43b9-91bd-4901c8946e19)

With my suggestions of slight improvements:
![test](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/d2bc77ee-2a2f-46b2-8bd1-1f8f75e02fe3)

Though personally me I prefer minimalism of DuckDuckGo: perhaps it is possible to make it somehow like it is ☺
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/c01cd904-7e78-4dab-8a73-c195bbe8f9a6)

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/0adb7db1-507d-45d7-9873-8ff18c2fb74e)

**Comment by callmemagnus** [comment]
I will take your comments into consideration. (except the centering :-) of the search input ).

**Comment by ostasevych** [comment]
> I will take your comments into consideration. (except the centering :-) of the search input ).

Thanks! Why not centering?..

**Comment by callmemagnus** [comment]
I made some layout change for the result presentation. I'll look into the search box later as part of its revamp. I'll release when you push the Ukrainian translations.

**Comment by callmemagnus** [comment]
v1.2.0-pre on develop contains most changes. I will release soon. Please have a look at the uk labels.
