### ISSUE TITLE
Prioritise the list of providers

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#14]
I suggest to prioritise the list of providers in the drop-down selector according to the order of apps on the navigation bar, eg usually Files is more prioritised.

**Comment by callmemagnus** [comment]
This app just uses the list of providers returned by your instance (/ocs/v2.php/search/providers) and then uses the search API (/ocs/v2.php/search/providers/<provider_name>/search?term=admin).

The list is ordered somehow. Don't know where that order comes from.

**Comment by ostasevych** [comment]
> This app just uses the list of providers returned by your instance (/ocs/v2.php/search/providers) and then uses the search API (/ocs/v2.php/search/providers/<provider_name>/search?term=admin).
> 
> The list is ordered somehow. Don't know where that order comes from.

I see... I've created a feature request at https://github.com/nextcloud/server/issues/41243
Perhaps it is possible to analyse other user or admin settings as a workaround?

**Comment by callmemagnus** [comment]
This is what the endpoint returns:

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/232478/2a77def8-3c40-40a5-b28c-29a245adf51a)

There is definitely something somewhere.

If one day get comfortable with the whole nextcloud backend code, I might add a configuration panel for admins to define order and mask providers.
