### ISSUE TITLE
Improvements to the Contacts provider

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#16]
Please, consider adding more details to the results when Contacts provider is chosen if present, at least, phone number, locality, birthday. By now only email is shown.

**Comment by callmemagnus** [comment]
Would be great but the data is not provided out of the box by the search API.

If Nextcloud provides an API to make this seamless for consumers of their API, yes.
Else it will just be hack around other applications...

This app just uses the list of providers returned by your instance (/ocs/v2.php/search/providers) and then uses the search API (/ocs/v2.php/search/providers/<provider_name>/search?term=admin).
