### ISSUE TITLE
[BUG] News Feed is not loaded when clicking on news result

### ISSUE THREAD

**Issue by meichthys** [callmemagnus/nextcloud-searchpage#17]
**Describe the bug**
This may be more of a News app issue, but when clicking on a news result, the news app is loaded but the article is not. The news app is just blank (other than the side menu).

**To Reproduce**
1. Go to search page
2. Search for something in the news
3. Click the news result
4. Try to read the news article

**Expected behavior**
The news article should be displayed

**Screenshots**
Search Results:
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/10717998/d4242ad1-716d-4d8f-a05e-19e447d99d5d)

After clicking on the search result:
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/10717998/43c37797-739a-45f4-84d1-d0663c1995c8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by callmemagnus** [comment]
Hello,

I checked, you are right that it the implementation of the search provider of the News API that is broken.

I logged https://github.com/nextcloud/news/issues/2408.

**Comment by callmemagnus** [comment]
@meichthys are you using the alpha version (25) of News ?

As said in the related upstream bug, the 24 is supposed to work properly but only linking to feeds not yet to feed items.

**Comment by callmemagnus** [comment]
I'm closing this as this is completely handled upstream.
