### ISSUE TITLE
Update/input Info on Nextcloud Apps Store

### ISSUE THREAD

**Issue by daffydock** [callmemagnus/nextcloud-searchpage#19]
Hi, 

Really like where the app is going. This is more of an administrative issue, rather than a technical one. Noticed that some info has not been entered into the NC App store. 

https://apps.nextcloud.com/apps/thesearchpage

Compared to say:

https://apps.nextcloud.com/apps/notes

Specifically, your name/handle, site page, if there is one but also the support page, or link to this Github. Which makes it easier for people to submit issues. 

I have been using NC  for many years now and some Apps certainly come across as more shifty or questionable than others. This affects the rate of installs and in turn the rate of reviews. As you can imagine, more reviews will incentivize more installs. 

And as such, and as it stands, if something breaks then there is no apparent recourse for the average end user. So people tend to install them less as a way to avoid breakage.  

I use Github daily, I looked a the zip file and was able to find info towards your repository. Not all users may be able, know or have the desire to do that. If it is okay with you, perhaps may you be able to fill those missing info sets? It also makes it easier to find your repository, since I had to search for your github handle, not the app name. Since if you do that, you usually will get Nextcloud's search or their own, larger repo collection instead as main hits, over yours.  

Lastly, I really like your app. I have thousands of notes and files and it makes it far easier to find them over using the far more limited, both in usability and in on-screen real estate of the built-in NC one.  

 Cheers.

**Comment by callmemagnus** [comment]
Thanks. 

Yes, you are right I will look at this as soon as possible

**Comment by callmemagnus** [comment]
Thanks. 

Yes, you are right I will look at this as soon as possible.

As a side note, my name is there as is the link to this GitHub (as a links at the bottom of the store page)

![Screenshot_2023-11-07-21-36-18-68_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/callmemagnus/nextcloud-searchpage/assets/232478/c71dec92-c2c7-4f93-8df8-021e12f79f58)

**Comment by daffydock** [comment]
That's fair. I am in the habit of simply downloading the zip files and going through them from command line. Also, just checked, perhaps it might be my browser Librewolf blocking the script but I do not see those buttons there. Not sure why. 

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/32020577/7938ee8b-5f54-4608-8819-fa15cdc02821)
 
Noticed you updated the entries, thus if you do not mind, I will close this issue. 
Lastly, thanks again for the app. Hope more people find out about it.

**Comment by callmemagnus** [comment]
I took the screenshot the day before they changed the layout.
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/232478/3b9f6553-e683-4a92-9f23-26dbbac386ea)

It is in the right column with the blueish background.

**Comment by daffydock** [comment]
There may be a mix up. There was always some info that could be placed on the right hand side before the change of layout. As per example, below, which was missing before and the reason I opened the issue in the first place. It was mostly empty before the site update. 

The existence of the buttons outside of that were never the issue and it may a point of a mix up since we are talking about almost the same thing that is seemingly being slightly obfuscated by the timing of the site being redesigned. 

Cheers. 

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/32020577/762b67e1-3b79-4e50-8eb9-11f65c4ca77c)
