### ISSUE TITLE
Add the localisation process to Transifex

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#20]
Would that be possible to start using the localisation of the app with the help of Transifex, as it is mostly done by NC apps?

**Comment by callmemagnus** [comment]
https://app.transifex.com/magooweb/nextcloud-thesearchpage/dashboard/

**Comment by ostasevych** [comment]
Actually, I was looking for it over here https://app.transifex.com/nextcloud/nextcloud/
Why haven't you added it to the Nextcloud family?

**Comment by callmemagnus** [comment]
>  Why haven't you added it to the Nextcloud family?

Just because I was lazy and that integration takes some time.

**Comment by ostasevych** [comment]
> > Why haven't you added it to the Nextcloud family?
> 
> Just because I was lazy and that integration takes some time.

Can I help you with that? ;)

**Comment by callmemagnus** [comment]
No, it just takes some time and an admin to configure stuff on Nextcloud side.

I made a comment on one of your PRs.
