### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by TtuxX** [callmemagnus/nextcloud-searchpage#26]
**Is your feature request related to a problem? Please describe.**
User cannot fully enjoy the new changes when there is an app update as he it not aware of them (no changelog section on user's NC instance in the apps section, no changelog in NC app store website, and no changelog on Github apart from digging into the commits)

**Describe the solution you'd like**
I would love to see a changelog a bit like this:
https://github.com/nextcloud/desktop/blob/master/CHANGELOG.md

**Describe alternatives you've considered**
Digging into the commits

**Additional context**
NA.

**Comment by callmemagnus** [comment]
Added. Will appear in next release.
