### ISSUE TITLE
Previews are not showing up

### ISSUE THREAD

**Issue by Piefje01** [callmemagnus/nextcloud-searchpage#29]
Showing preview on images.

**Comment by callmemagnus** [comment]
Please elaborate a little your expectations for this.

**Comment by Piefje01** [comment]
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/92102916/607d28cb-1e62-4190-9e1a-f94e90f93511)

**Comment by Piefje01** [comment]
You seen no preview when searching on for example tif.
Also possible to search on date/tag/metadata "option box"

**Comment by callmemagnus** [comment]
> Also possible to search on date/tag/metadata "option box"

Request that feature to the upstream provider application. This application has no control over how the search term is used by the different providers. Please look at https://github.com/callmemagnus/nextcloud-searchpage/blob/main/README.md#philosophy-of-this-application.

> Preview

I'll check why it does not show the provided thumbnail.

**Comment by callmemagnus** [comment]
will be in v1.2.2

**Comment by Piefje01** [comment]
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/92102916/91e582d2-746d-4f62-83da-488f71adc9d4)

Almost :-)

**Comment by callmemagnus** [comment]
Can you check the response of the providers for those items? 

As far as I can guess, that is the fulltextsearch provider and it does not return a valid `thumbnailUrl`.

```
{
	"0": {
		"thumbnailUrl": "",
		"title": "(files) abc",
		"subline": "somewhere/a/image.jpg",
		"resourceUrl": "/apps/files/?dir=/somewhere/a&scrollto=image.jpg",
		"icon": "/apps/theming/img/core/filetypes/image.svg?v=62260f84",
		"rounded": false,
		"attributes": []
	}
}
```

I would greatly appreciate if you could report it as a bug on their project.

**Comment by Piefje01** [comment]
I think your right
