### ISSUE TITLE
[BUG] Ukrainian localisation is missing after the update to 1.2.2

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#30]
The Ukrainian localisation files uk.js and uk.json are missing in the latest update to v.1.2.2 as of today. Please, check.

**Comment by callmemagnus** [comment]
I know I have the same issue for French. I mentioned it in the changelog.

As we moved to transifex, all existing translations got deleted.
Somehow, the translation at https://app.transifex.com/nextcloud/nextcloud/thesearchpage/ must be reviewed before they are pushed in this repo.

I have no clue how this happens.

**Comment by callmemagnus** [comment]
Great. As soon at it is sync'd I'll do a release.

How can one review there ? I can't (or I'm not able to find where)

**Comment by ostasevych** [comment]
I've just reviewed all the translations myself, as I am a sole Ukrainian translator here :)

![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/93644349-a21b-48e5-b6fc-78fdee07511c)

**Comment by callmemagnus** [comment]
Lucky you!

I don't have bulk action. I can't event approve my own application translations in one of my languages...

**Comment by maghog** [comment]
Same for Swedish...

**Comment by callmemagnus** [comment]
v1.2.4 fixes ukrainian.

I opened an issue about the sync tool not updating the translations (https://github.com/nextcloud/docker-ci/issues/614). No update yet.
