### ISSUE TITLE
Display search results number and extend Actions functionality to results

### ISSUE THREAD

**Issue by damnshaneisthatu** [callmemagnus/nextcloud-searchpage#31]
Thank you for your work on this app!

**Is your feature request related to a problem? Please describe.**
Currently, users are unable to perform actions on search results. E.g. selecting one or more results and then moving them
<img width="790" alt="Screenshot 2023-12-06 at 6 31 53 AM" src="https://github.com/callmemagnus/nextcloud-searchpage/assets/1761752/6aa7aa34-1423-4708-92e6-710f2b4c1140">

**Describe the solution you'd like**
1. Extend the Actions capabilities to search results
2. Display search results number instead of "Files" 

Proposed solution mockup:
![Suggestions](https://github.com/callmemagnus/nextcloud-searchpage/assets/1761752/5579fb14-8c9a-4642-8816-c549271f1bb8)

**Comment by callmemagnus** [comment]
Hello,

Thanks for taking the time to provide your suggestions!

With the current way of working, there is no way to get the count as it is not provided by the SearchProviders.

This application leverages the existing services (SearchProviders) that Nextcloud applications can implement. Every application will implement it differently and are only bound to provide certain data for each result. Sadly the count is not part of it.

To add it, Nextcloud's interfaces must be changed and all applications must implement it :-(

Regarding the actions, I see no simple way to do this. As far as I have seen, this is no list of actions that can be performed on a result item. For the same reason as above, this depends on the application and is usually implemented in their respective screens with no way to get that information.

I could look into doing something for specifically for `Files` application but cannot promise anything. I'm afraid it will create version dependencies that I cannot afford the time to maintain.

**Comment by damnshaneisthatu** [comment]
Thanks for taking a look, @callmemagnus! I figured it might be a long shot.
