### ISSUE TITLE
Theme: Avoid double hover effect (dark theme)

### ISSUE THREAD

**Issue by solracsf** [callmemagnus/nextcloud-searchpage#33]
When using Nextcloud **dark theme**, there is a double hover effect that could be avoided.

See screenshots:

### No hover
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/12234510/1f213685-ce50-40c9-acdc-ae66ccce4791)

### Hover on the edge of the result (OK)
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/12234510/7699ad60-6942-4d3d-a97c-73cb728839a3)

### Hover on the middle of result (should be removed to keep only the previous hover effect)
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/12234510/37cec216-dbf9-4782-a35e-c1a230475a1a)

Beside that, the hover could have rounded corners to keep the overall nextcloud rounded corners (border-radius).

**Comment by callmemagnus** [comment]
Fixed in v1.2.4 and v1.3.0-pre4
