### ISSUE TITLE
[EVOLUTION] Add a Clear button

### ISSUE THREAD

**Issue by solracsf** [callmemagnus/nextcloud-searchpage#34]
Add a "Clear" button to improve UI.

### Before
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/12234510/20f608aa-3de7-4a4d-87a9-3b2c12d6a159)

### After
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/12234510/f68b6cd5-88ac-4755-bd9b-053aebb4b100)

The desired behaviour is the same than the little cross on the right of the search box _(but a button is more User Friendly IMHO)_.

**Comment by callmemagnus** [comment]
Thank you for the suggestion.

I believe the cross is sufficient for the moment: it is widely understood and provides the functionality.

Are you referring to any study in particular to back the fact that a clear button it is more user-friendly ?

Don't misunderstand me, I'm really interested in literature that backs your request. 
If you look at previous issues on this project, you'll find one that requests the removal of the clear button that was there; user friendliness seems to be very relative.

I'm closing this for now, feel free to reopen with more information to help me chose the best solution.

**Comment by solracsf** [comment]
No problem :)

IMO the button makes sense because it clears **the whole page** (and it's a good thing), not only the search box (where the 'x' stands).

See also https://medium.com/@ux.fionalim/the-clear-button-in-search-a-key-consideration-97b2f836e322
