### ISSUE TITLE
[BUG] the search page does not work anymore since Nextcloud 28.x (maybe 29)

### ISSUE THREAD

**Issue by JosefAschauer** [callmemagnus/nextcloud-searchpage#37]
**Describe the bug**

clicking the serch icon, which gave me wunderful search experience in the past, does simply nothing now but reloading the current nextcloud page - no search window appears anymore

Instance: AIO, nextcloud 19.03, behavior started back in 18.x
uninstalling / removing and reinstalling does not help

**Comment by callmemagnus** [comment]
Hello,

This is strange. I'm using docker Nextcloud 28 and upgraded recently to 29 without issues. But not the AIO version.

The click on the app icon should be handled by Nextcloud. The icon is just a link on my instances. Clicking on the link redirects the user to this application page (/apps/thesearchpage/).

How do you install this application ? Manually or from the /settings/apps ?

Can you check that the URL is correct on the icon ?
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/232478/81941ad4-9200-4880-91ea-a7478b3c2d3c)

If you send me a HAR file of what is happening when you click and it reloads the page, it would help me spot if the issue is on the application.

Do you have plugins that changes the way the menu is presented ?

Lastly, is there any errors in the logs of Nextcloud ?

Thanks in advance

**Comment by JosefAschauer** [comment]
Hi,

Thanks for picking this up!
The link on the icon points to my nextcloud URL is changing, dependent on where I am in the navigation (ie /settings/apps/search when I’, in /settings/apps, /apps/files/files if I click it in the files menu. This is apparently wrong...how do I fix it?

Please find the har file here:
https://nc.abraxas.dyn-dns.org/s/FKrrA9oqW5yQcMn

The app was installed via settings/apps
I have no app installed which changes the layout
Icon seems correct
No errors in the log (just OCR related from tesseract)


Best,
Josef

**Comment by JosefAschauer** [comment]
PS: if I deliberately enter /apps/thesearchpage in the browser, thesearchpage opens just fine. Seems the icon is really just missing a proper link.

Seems fulltextseach is also having some hickups since some time. As soon as I click on a file in the result list, it just opens the folder with the file, underlaying action is &scrollto

From: Josef Aschauer
Sent: Tuesday, 2 July 2024 18:31
To: 'callmemagnus/nextcloud-searchpage' ***@***.***>; 'callmemagnus/nextcloud-searchpage' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [callmemagnus/nextcloud-searchpage] [BUG] the search page does not work anymore since Nextcloud 28.x (maybe 29) (Issue #37)


Hi,

Thanks for picking this up!
The link on the icon points to my nextcloud URL is changing, dependent on where I am in the navigation (ie /settings/apps/search when I’, in /settings/apps, /apps/files/files if I click it in the files menu. This is apparently wrong...how do I fix it?

Please find the har file here:
https://nc.abraxas.dyn-dns.org/s/FKrrA9oqW5yQcMn

The app was installed via settings/apps
I have no app installed which changes the layout
Icon seems correct
No errors in the log (just OCR related from tesseract)


Best,
Josef

**Comment by callmemagnus** [comment]
Oddly enough, I have now the same issues, but not always (?) on this application but several others too.

I filed a bug upstream to get their recommendations.

**Comment by JosefAschauer** [comment]
Hi,
Seems the bug I reported for thesearchpage not loading is also caused by fulltextsearch.
Once you disable the navigation icon, all works as expected.

***@***.***

Found here:
https://github.com/nextcloud/fulltextsearch/issues/842

Best,
Josef

**Comment by JosefAschauer** [comment]
Hi, could you please remove my url from my last email?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by callmemagnus** [comment]
I redacted your comment but you can do it yourself through github's interface.

**Comment by JosefAschauer** [comment]
many thanks callmemagnus, haven't had my github login with me while on mobile.

**Comment by cociweb** [comment]
Hi,
As a workaround (which is recommended in our case), please disable the navigation icon of the original Full Text Search. As recommended here:
https://github.com/nextcloud/fulltextsearch/issues/842#issuecomment-2139337918

**Comment by JosefAschauer** [comment]
Thanks mate, already done werks ago;)

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
