### ISSUE TITLE
[EVOLUTION] Search in emails

### ISSUE THREAD

**Issue by cociweb** [callmemagnus/nextcloud-searchpage#38]
Hello, First of all, let me express my respect to the creators about this plugin.

It just came into my mind the possibility to search in the emails (and in their attachments). Is it possible in theory? Is there any searchable email provider?

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Search results from email (and in attachments)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by callmemagnus** [comment]
Any provider available on your install should also be available on the application.

I would suggest that you get in touch with the application developers who maintain the email application you are using and ask them to implement a search provider.

I am closing this issue.
