### ISSUE TITLE
[EVOLUTION] the results should always display a (modification) date (of files)

### ISSUE THREAD

**Issue by ferdiga** [callmemagnus/nextcloud-searchpage#41]
**Philosophy of this application**

Version 1.2.7

the Mail provider shows the Mail date, 
all other providers should also show a date (modification date for files)

very often one can guess the right file from the modification date

**Comment by callmemagnus** [comment]
hello,

Thanks for the suggestions.

Only information returned by the provider could eventually be used to be displayed.

This application relies on the other providers contract implementation. As far as I know, that includes:

- a thumbnailUrl - files sets this to ""
- a title
- a subline
- a resourceUrl - the target url used, usually https://<your.server>/f/<fileid>
- an icon
- attributes (this is open-bar as different for each applications)

no dates are part of the contract (AFAIK).

Files provides as attributes:
- fileId - a number
- path - "direct" path

Currently, I don't have bandwidth to create specific behavior/display rules per provider. implementing such setup requires to know the contracts of each implementation version of each provider supported, follow release cycles of each providers and maintain that compatibility across version.

Regards,
