### ISSUE TITLE
[EVOLUTION] Option to starting the search in the current directory  or complete database

### ISSUE THREAD

**Issue by ferdiga** [callmemagnus/nextcloud-searchpage#42]
**Philosophy of this application**

v 1.2.7

start the search in the current directory - (i.e. place a menu next to recent to catch the current context)

If the directory structure is hierarchical it's very likely that the user wants to search only in "this" part of the directory. 
Example:
* search in one of many companies
* search in one of many projects
* search in one of many fiscal years.
etc

**Comment by callmemagnus** [comment]
Hello,

Sorry for the delay.

I think you are talking about the search provided by nextcloud on the right side of the screen.

I say that as this application has no notion of context as it is its own page on your nextcloud instance.

Am I correct ?

**Comment by ferdiga** [comment]
<img width="338" alt="20241021 000005 Files - Private Storage Share" src="https://github.com/user-attachments/assets/9ea407b7-ce99-4f9a-97da-95e5e300562b">
Hi - IMO the URL provides the context = the current directory.
Apple provides 2 options 

- current directory
- all directories

 my preferred option is to start searching in the current directory - and if the result is not satisfactory - search all.
 
 BTW it would be very helpful to return the last modification date in the search result
 One of my databases contains data of about 20 years and without the modification date (or creation date?) the results of the query are not sufficiently specific.
 As opening a file replaces the search tab/window it is not possible to go "BACK" to the search window.
 The search is a very cumbersome help.

**Comment by callmemagnus** [comment]
Hi again, 

this application is only the magnifier icon available on the app list in your screenshot and a full page app.
The magnifier on the right is the search provided by Nextcloud.

This application has no knowledge about the page you were before you clicked on the app icon.

Bringing in the possibility to pick the referrer and try to guess the app (and relative path in the said app) based the previous page is out of scope of this application.

Regarding result content, I agree it would be great to have the last modified date, please file a request to Nextcloud server to change the search result contract as the last modified date is not available in the search results. Currently (v30), this is what the application receives:

Files:

![image](https://github.com/user-attachments/assets/920cfe3e-930c-4327-a263-0ea37068528d)

Fulltextsearch:
![image](https://github.com/user-attachments/assets/2c2b2bf4-5dba-4c36-8332-4b341288d12a)

Regards,

**Comment by ferdiga** [comment]
well, then it would help to open the search results in an new window/tab.
